#!/usr/bin/env python3    查看excel中有几个sheet，每个sheet几行几列叫什么名字
import sys
from xlrd import open_workbook

input_file=sys.argv[1]
workbook=open_workbook(input_file)
print('Number of worksheets:',workbook.nsheets)
for worksheet in workbook.sheets():
    print("Worksheet name:",worksheet.name,"\tRows:",\
          worksheet.nrows,"\tColumns:",worksheet.ncols)
