#!/usr/bin/env python3    功能是复制一个excel表单中的sheet
import sys
from xlrd import open_workbook
from xlwt import Workbook
input_file=sys.argv[1]   #源文件
output_file=sys.argv[2]    #新建文件
output_workbook=Workbook()
output_worksheet=output_workbook.add_sheet('jan_2013_output')#新excel文件中sheet名字
with open_workbook(input_file) as workbook:
    worksheet=workbook.sheet_by_name('推荐类型')    #被复制xlsx文件中目标sheet的名字
    for row_index in range(worksheet.nrows):
        for column_index in range(worksheet.ncols):
            output_worksheet.write(row_index,column_index,\
                                   worksheet.cell_value(row_index,column_index))
output_workbook.save(output_file)
